# Generated by Django 3.2.7 on 2021-11-13 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_auto_20211112_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideas',
            name='joined_users',
        ),
    ]
