# Generated by Django 3.2.7 on 2021-12-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
