# Generated by Django 3.2.7 on 2021-12-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(default=0, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('html_link', models.CharField(max_length=255)),
                ('created_time', models.CharField(max_length=255)),
                ('updated_time', models.CharField(max_length=255)),
                ('start_time', models.CharField(max_length=255)),
                ('end_time', models.CharField(max_length=255)),
                ('attendee_name', models.CharField(max_length=255)),
                ('attendee_email', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'event_list',
            },
        ),
    ]
