# Generated by Django 3.2.7 on 2021-12-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_event_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_list',
            name='formaldressCode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event_list',
            name='petsAllowed',
            field=models.BooleanField(default=True),
        ),
    ]
